name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.3.1
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: ^2.5.4
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  flutter_chat_types:
    git: 
      url: https://github.com/ebb-flow-group/flutter_chat_types
      ref: voice_message
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
